<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/ServicioAviso/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ServicioAviso" targetNamespace="http://www.example.org/ServicioAviso/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.example.org/ServicioAviso/" xmlns:Q1="http://www.example.org/tipos">
            <xsd:import schemaLocation="tipos.xsd" namespace="http://www.example.org/tipos"></xsd:import>
            <xsd:element name="crear">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="aviso" type="Q1:Aviso" maxOccurs="1" minOccurs="1"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="crearResponse">
        <xsd:complexType>
          <xsd:sequence>
          	<xsd:element name="ok" type="xsd:boolean" maxOccurs="1"
          		minOccurs="1" />
          	<xsd:element name="error" type="xsd:string" maxOccurs="1"
          		minOccurs="0">
          	</xsd:element>
          	<xsd:element name="idAviso" type="xsd:int" maxOccurs="1" minOccurs="0"></xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name="consultar">
      	<xsd:complexType>
      		<xsd:sequence>
      			<xsd:element name="idAviso" type="xsd:int" maxOccurs="1" minOccurs="1"></xsd:element>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
      <xsd:element name="consultarResponse">
      	<xsd:complexType>
      		<xsd:sequence>

      			<xsd:element name="ok" type="xsd:boolean" maxOccurs="1" minOccurs="1"></xsd:element>
      			<xsd:element name="error" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
      			<xsd:element name="aviso" type="Q1:Aviso" maxOccurs="1" minOccurs="0"></xsd:element>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="crearRequest">
    <wsdl:part element="tns:crear" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="crearResponse">
    <wsdl:part element="tns:crearResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="consultarRequest">
  	<wsdl:part name="parameters" element="tns:consultar"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="consultarResponse">
  	<wsdl:part name="parameters" element="tns:consultarResponse"></wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ServicioAviso">
    <wsdl:operation name="crear">
      <wsdl:input message="tns:crearRequest"/>
      <wsdl:output message="tns:crearResponse"/>
    </wsdl:operation>
    <wsdl:operation name="consultar">
    	<wsdl:input message="tns:consultarRequest"></wsdl:input>
    	<wsdl:output message="tns:consultarResponse"></wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServicioAvisoSOAP" type="tns:ServicioAviso">

  	<soap:binding style="document"
  		transport="http://schemas.xmlsoap.org/soap/http" />
  	<wsdl:operation name="crear">

  		<soap:operation
  			soapAction="http://www.example.org/ServicioAviso/crear" />
  		<wsdl:input>

  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use="literal" />
  		</wsdl:output>
  	</wsdl:operation>
  	<wsdl:operation name="consultar">

  		<soap:operation
  			soapAction="http://www.example.org/ServicioAviso/consultar" />
  		<wsdl:input>

  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use="literal" />
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ServicioAviso">
    <wsdl:port binding="tns:ServicioAvisoSOAP" name="ServicioAvisoSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
